@extends('layouts.app')

@section('title', 'Community Examples - StoryBook')

@section('content')
<div class="bg-gray-50 min-h-screen py-16">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
            <h1 class="text-3xl font-extrabold text-gray-900 sm:text-4xl">Community Gallery</h1>
            <p class="mt-4 text-xl text-gray-500">See the magical personalized stories generated by our users.</p>
        </div>

        @if(empty($files))
            <div class="bg-white rounded-2xl p-12 text-center border border-gray-200 shadow-sm max-w-2xl mx-auto">
                <svg class="mx-auto h-16 w-16 text-gray-300 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                <h3 class="text-xl font-bold text-gray-900">No examples yet</h3>
                <p class="mt-2 text-gray-500">Be the first to create a personalized story!</p>
                <div class="mt-8">
                    <a href="/story/create" class="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-xl text-white bg-indigo-600 hover:bg-indigo-700 shadow-sm transition">
                        Create Your Story Now
                    </a>
                </div>
            </div>
        @else
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                @foreach($files as $file)
                <div class="bg-white rounded-2xl overflow-hidden shadow-sm border border-gray-200 hover:shadow-lg transition-all flex flex-col">
                    <div class="aspect-[4/3] bg-gray-100 relative group">
                        <!-- Toolbar=0 prevents the PDF viewer headers, keeping it clean -->
                        <iframe src="{{ asset('storage/stories/' . $file) }}#toolbar=0&navpanes=0&scrollbar=0" class="w-full h-full pointer-events-none" frameborder="0"></iframe>
                        <!-- Overlay to prevent interaction with iframe inside the card -->
                        <!-- <div class="absolute inset-0 bg-transparent group-hover:bg-gray-900/5 transition-colors cursor-pointer" onclick="window.open('{{ asset('storage/stories/' . $file) }}', '_blank')"></div> -->
                        <div class="absolute inset-0 bg-transparent group-hover:bg-gray-900/5 transition-colors cursor-pointer"></div>
                    </div>
                    <div class="p-6 flex-grow flex flex-col justify-between">
                        <div>
                            <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 mb-3">
                                StoryBook PDF
                            </span>
                            <h3 class="text-xl font-bold text-gray-900 mb-2 truncate" title="{{ $file }}">
                                {{ ucfirst(explode('_', $file)[1] ?? 'Magical') }}'s Adventure
                            </h3>
                        </div>
                        <a href="{{ asset('storage/stories/' . $file) }}" target="_blank" class="mt-6 w-full inline-flex justify-center items-center px-4 py-2.5 border border-gray-300 shadow-sm text-sm font-semibold rounded-xl text-gray-700 bg-white hover:bg-gray-50 hover:text-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition">
                            Read Full Story &rarr;
                        </a>
                    </div>
                </div>
                @endforeach
            </div>
        @endif
    </div>
</div>
@endsection
